[build]
  command = "ng build --base-href=/"
  publish = "dist/collage-amor"

[[plugins]]
  package = "@netlify/angular-runtime"
  inputs = { disabled = true }
[build.environment]
  NETLIFY_USE_PLUGIN = "false"
